name: 'Create emulator, launch it then run the input script'
description: 'Launches an Android emulator and runs the input script'
inputs:
  script:
    description: 'Script runs after successful launch of the emulator'
    required: false

runs:
  using: 'composite'
  steps:
      - name: Set Up Required Path System Variables for essential tools
        # Adds path for essential tools like sdkmanager, avdmanager, emulator, etc.
        run: |
            echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.2" >> $GITHUB_PATH
        shell: bash

      - name: SDK package licenses agreement
        run: |
          chmod +x ./.github/scripts/accept_sdk_licenses.sh
          ./.github/scripts/accept_sdk_licenses.sh
        shell: bash

      - name: Install System Image
        run: |
            sdkmanager --install 'system-images;android-30;google_apis_playstore;x86_64'
        shell: bash

      - name: Create Emulator
        id: create_emulator
        # Create an emulator using avdmanager and do not create custom hardware profile by answering "no" to the prompt
        run: echo "no" | avdmanager create avd -n TestEmulator30 -k "system-images;android-30;google_apis_playstore;x86_64"
        shell: bash

      - name: Check Emulator Creation Status
        run: |
          if [ $? -eq 0 ]; then  # Verfies the exit status of the last executed command i.e. "create_emulator", if it is 0 then the emulator is created succesfully
            echo "Emulator creation successful"
          else
            echo "Emulator creation failed"
            exit 1
          fi
        shell: bash

      - name: Restart adb server
        run: |
          adb kill-server
          adb start-server
        shell: bash

      - name: Launch Emulator
        run: |
          echo "~~~~~~ Starting emulator and waiting for boot to complete.... ~~~~~~"
          $ANDROID_HOME/emulator/emulator -avd TestEmulator30 -no-skin -no-audio -no-window &
          adb wait-for-device  # Waits until emulator is connected and ready/responsive to accept commands
          echo "~~~~~~ Emulator has finished booting ~~~~~~"
        shell: bash

      - name: Build App
        run: |
          chmod +x gradlew
          ./gradlew installDebug
        shell: bash

      - name: Run script if provided
        if: inputs.script != ''
        run: bash -c "${{ inputs.script }}"
        shell: bash
